"""initial schema

Revision ID: 5e3d2b4e6efc
Revises: 
Create Date: 2026-07-08 18:29:17.149976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3d2b4e6efc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('daily_sales_product_id_sale_date_key'), 'daily_sales', type_='unique')
    op.drop_constraint(op.f('product_ingredients_product_id_ingredient_id_key'), 'product_ingredients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('product_ingredients_product_id_ingredient_id_key'), 'product_ingredients', ['product_id', 'ingredient_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('daily_sales_product_id_sale_date_key'), 'daily_sales', ['product_id', 'sale_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
