// frontend/src/features/landing/landing-kit/LegalModals.jsx
import { useEffect } from 'react';
import { FaLock, FaShieldAlt } from 'react-icons/fa';
import { FiX } from 'react-icons/fi';
import './landing-kit.css';

const TERMS_SECTIONS = [
  {
    h: '1. Acceptance of Terms',
    p: [
      'By accessing or using ChefDuo Forecast, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. If you do not agree with any part of these Terms, you must discontinue use of the system.',
      'ChefDuo reserves the right to update or modify these Terms and Conditions at any time. Any changes will take effect upon publication within the system. Your continued use of ChefDuo Forecast after such changes constitutes your acceptance of the revised Terms.',
    ],
  },
  {
    h: '2. Data Collection and Privacy',
    p: [
      'ChefDuo Forecast collects and processes information necessary for system functionality, including user account information, sales and transaction records, product and inventory data, ingredient usage data, and system usage information.',
      'The collected information is used solely to generate sales forecasts and demand predictions, produce inventory and ingredient recommendations, improve forecasting accuracy and system performance, and generate reports and analytics.',
      'ChefDuo does not sell, rent, or disclose user information to third parties except when required by law.',
      'All personal information is collected, processed, stored, and protected in accordance with the Data Privacy Act of 2012 (Republic Act No. 10173) and its Implementing Rules and Regulations.',
      'Reasonable administrative, technical, and organizational safeguards are implemented to protect user information from unauthorized access, alteration, disclosure, or loss.',
    ],
    list: [
      'User account information',
      'Sales and transaction records',
      'Product and inventory data',
      'Ingredient usage data',
      'System usage information',
    ],
  },
  {
    h: '3. System Usage',
    p: [
      'ChefDuo Forecast is designed to assist businesses in forecasting sales demand and estimating ingredient requirements using historical sales data.',
      'The forecasts and recommendations generated by the system are intended to support business planning and decision-making. While predictive analytics are used to improve forecasting accuracy, all results are estimates and should not be considered guarantees of future performance.',
      'Actual sales and inventory requirements may vary due to market conditions, customer demand, seasonal factors, supplier availability, and other circumstances beyond the system’s control.',
    ],
  },
  {
    h: '4. User Responsibilities',
    p: [
      'Users are responsible for providing accurate, complete, and up-to-date information, maintaining the confidentiality of their account credentials, and using the system only for lawful and authorized purposes.',
      'Users shall not attempt to gain unauthorized access to the system or its database, upload malicious software or harmful content, interfere with the operation or security of the system, or use the system in violation of applicable laws and regulations.',
    ],
  },
  {
    h: '5. Disclaimer',
    p: [
      'ChefDuo Forecast is provided as a decision-support tool. Although reasonable efforts are made to produce accurate forecasts and recommendations, the system does not guarantee the accuracy, completeness, or reliability of its predictions.',
      'Users acknowledge that forecasting results should be used alongside professional judgment and other relevant business considerations. The developers are not responsible for business decisions or losses resulting from reliance on the system’s forecasts or recommendations.',
    ],
  },
  {
    h: '6. Governing Law',
    p: [
      'These Terms and Conditions shall be governed by and interpreted in accordance with the laws of the Republic of the Philippines, including Republic Act No. 10173 (Data Privacy Act of 2012) and Republic Act No. 8792 (Electronic Commerce Act of 2000).',
      'Any dispute arising from the use of ChefDuo Forecast shall first be resolved through good-faith discussion. If no resolution is reached, the matter shall be subject to the jurisdiction of the appropriate courts of the Republic of the Philippines.',
    ],
  },
];

const PRIVACY_SECTIONS = [
  {
    h: '1. Information We Collect',
    p: [
      'ChefDuo Forecast collects only the information necessary to provide forecasting and analytics services.',
      'Personal information includes your name, email address, contact number, and account credentials.',
      'Business information includes product and menu information, sales transaction records, inventory and ingredient data, and historical sales records used for forecasting.',
      'System information includes your IP address, browser or device information, and login activity and system logs.',
    ],
  },
  {
    h: '2. How We Use Your Information',
    p: [
      'The information collected is used solely to generate sales forecasts and ingredient demand predictions, produce reports and analytics, improve forecasting accuracy and system performance, maintain the security and functionality of the system, and provide technical support when necessary.',
      'ChefDuo Forecast does not sell, rent, or share personal information with third parties for advertising or marketing purposes.',
    ],
  },
  {
    h: '3. Data Protection and Retention',
    p: [
      'Reasonable administrative, technical, and organizational measures are implemented to safeguard personal information against unauthorized access, disclosure, alteration, or loss. Access to personal information is limited to the account holder and authorized system administrators.',
      'Personal information will be retained only for as long as necessary to fulfill the purposes of the system or as required by applicable laws and institutional policies. When no longer required, the information will be securely deleted or disposed of.',
    ],
  },
  {
    h: '4. Disclosure of Information',
    p: ['Personal information will not be disclosed to third parties except:'],
    list: [
      'When required by law',
      'With the user’s consent',
      'To protect the security and integrity of the system',
    ],
  },
  {
    h: '5. Your Rights',
    p: [
      'In accordance with the Data Privacy Act of 2012 (Republic Act No. 10173), users have the right to access their personal information, request correction of inaccurate or incomplete information, request deletion of personal information subject to applicable legal requirements, and file a complaint with the National Privacy Commission (NPC) if they believe their privacy rights have been violated.',
    ],
  },
  {
    h: '6. Cookies',
    p: [
      'ChefDuo Forecast may use cookies or similar technologies to maintain user sessions and improve system functionality. These cookies are used solely for operational purposes and not for advertising or marketing. Users may manage cookie settings through their web browser; disabling cookies may affect certain system features.',
    ],
  },
  {
    h: '7. Data Breach Notification',
    p: [
      'In the event of a data breach involving personal information, ChefDuo Forecast will take appropriate measures to contain the incident and notify affected users and the National Privacy Commission when required under the Data Privacy Act of 2012.',
    ],
  },
  {
    h: '8. Contact Information',
    p: ['For questions or concerns regarding this Privacy Policy, please contact:'],
    list: ['Email: BCF@gmail.com', 'Address: Pasig City, Metro Manila, Philippines'],
  },
];

function LegalModal({ onClose, icon, title, intro, sections, agreeLabel }) {
  // Prevent background scroll while open
  useEffect(() => {
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    const onKey = (e) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', onKey);
    return () => {
      document.body.style.overflow = prev;
      window.removeEventListener('keydown', onKey);
    };
  }, [onClose]);

  return (
    <div className="lk-modal-overlay" onClick={onClose} role="presentation">
      <div
        className="lk-modal"
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
        aria-label={title}
      >
        <div className="lk-modal-head">
          <div className="lk-modal-head-left">
            <span className="lk-modal-ico">{icon}</span>
            <h2>{title}</h2>
          </div>
          <button
            type="button"
            className="lk-modal-close"
            onClick={onClose}
            aria-label="Close"
          >
            <FiX />
          </button>
        </div>

        <div className="lk-modal-body">
          <p className="lk-modal-intro">{intro}</p>
          {sections.map((s) => (
            <section key={s.h} className="lk-modal-sec">
              <h3>{s.h}</h3>
              {s.p.map((para) => (
                <p key={para.slice(0, 40)}>{para}</p>
              ))}
              {s.list && (
                <ul>
                  {s.list.map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              )}
            </section>
          ))}
        </div>

        <div className="lk-modal-foot">
          <button type="button" className="lk-btn lk-btn--primary" onClick={onClose}>
            {agreeLabel}
          </button>
        </div>
      </div>
    </div>
  );
}

export function TermsModal({ onClose }) {
  return (
    <LegalModal
      onClose={onClose}
      icon={<FaLock />}
      title="Terms and Conditions"
      agreeLabel="I Agree"
      intro="These Terms and Conditions govern your access to and use of ChefDuo Forecast. By accessing or using the system, you acknowledge that you have read, understood, and agreed to comply with these Terms. If you do not agree, you must discontinue use of the system."
      sections={TERMS_SECTIONS}
    />
  );
}

export function PrivacyModal({ onClose }) {
  return (
    <LegalModal
      onClose={onClose}
      icon={<FaShieldAlt />}
      title="Privacy Policy"
      agreeLabel="I Understand"
      intro="ChefDuo Forecast respects your privacy and is committed to protecting the personal information you provide. This Privacy Policy explains how your information is collected, used, stored, and protected in accordance with the Data Privacy Act of 2012 (Republic Act No. 10173) and its Implementing Rules and Regulations."
      sections={PRIVACY_SECTIONS}
    />
  );
}
